### ISSUE TITLE
Some problems with zio3==3.0.4

### ISSUE THREAD

**Issue by craudilho1199** [mo-xiaoxi/EmailSpoofingTestTool#2]
Hi bro!
I tried to run 'sudo pip install -r requirements.txt' in client mode, but it didn't work. A screenshot of the error from the terminal is attached.
![help_____________espoofing____________11111](https://user-images.githubusercontent.com/84741432/119511397-0c4e0980-bd7b-11eb-8a25-0d7ad39388f3.PNG)
![help_________________espoofing____________2222222](https://user-images.githubusercontent.com/84741432/119511419-1112bd80-bd7b-11eb-8f1f-981ad575911d.PNG)

What could be the problem?
Thank you for your prompt reply!
Best regards!

**Comment by craudilho1199** [comment]
Hello friend
I still need your help )

**Comment by wchhlbt** [comment]
Maybe you can try the command like this.
`pip3 install git+https://github.com/alset0326/zio3.git`

**Comment by mo-xiaoxi** [comment]
Hello, sorry for the late reply. Zio3 has been deprecated in our latest version, so this problem will no longer occur.
